// Team async-actions
export const GET_TEAM_LIST_START = 'GET_TEAM_LIST_START';
export const GET_TEAM_LIST_SUCCESS = 'GET_TEAM_LIST_SUCCESS';
export const GET_TEAM_LIST_FAILURE = 'GET_TEAM_LIST_FAILURE';

export const GET_TEAM_DETAILS_START = 'GET_TEAM_DETAILS_START';
export const GET_TEAM_DETAILS_SUCESS = 'GET_TEAM_DETAILS_SUCESS';
export const GET_TEAM_DETAILS_FAILURE = 'GET_TEAM_DETAILS_START';

// User async-actions
export const GET_USER_LIST_START = 'GET_USER_LIST_START';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE';

export const GET_USER_DETAILS_START = 'GET_USER_DETAILS_START';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';

// Search action
export const UPDATE_FILTER = 'UPDATE_FILTER';